/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StencilCounterApp {
    }
    interface StencilFetchApp {
    }
    interface StencilLitTodoApp {
    }
}
declare global {
    interface HTMLStencilCounterAppElement extends Components.StencilCounterApp, HTMLStencilElement {
    }
    var HTMLStencilCounterAppElement: {
        prototype: HTMLStencilCounterAppElement;
        new (): HTMLStencilCounterAppElement;
    };
    interface HTMLStencilFetchAppElement extends Components.StencilFetchApp, HTMLStencilElement {
    }
    var HTMLStencilFetchAppElement: {
        prototype: HTMLStencilFetchAppElement;
        new (): HTMLStencilFetchAppElement;
    };
    interface HTMLStencilLitTodoAppElement extends Components.StencilLitTodoApp, HTMLStencilElement {
    }
    var HTMLStencilLitTodoAppElement: {
        prototype: HTMLStencilLitTodoAppElement;
        new (): HTMLStencilLitTodoAppElement;
    };
    interface HTMLElementTagNameMap {
        "stencil-counter-app": HTMLStencilCounterAppElement;
        "stencil-fetch-app": HTMLStencilFetchAppElement;
        "stencil-lit-todo-app": HTMLStencilLitTodoAppElement;
    }
}
declare namespace LocalJSX {
    interface StencilCounterApp {
    }
    interface StencilFetchApp {
    }
    interface StencilLitTodoApp {
    }
    interface IntrinsicElements {
        "stencil-counter-app": StencilCounterApp;
        "stencil-fetch-app": StencilFetchApp;
        "stencil-lit-todo-app": StencilLitTodoApp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stencil-counter-app": LocalJSX.IntrinsicElements["stencil-counter-app"] & JSXBase.HTMLAttributes<HTMLStencilCounterAppElement>;
            "stencil-fetch-app": LocalJSX.IntrinsicElements["stencil-fetch-app"] & JSXBase.HTMLAttributes<HTMLStencilFetchAppElement>;
            "stencil-lit-todo-app": LocalJSX.IntrinsicElements["stencil-lit-todo-app"] & JSXBase.HTMLAttributes<HTMLStencilLitTodoAppElement>;
        }
    }
}
